name: Push a cada 15 minutos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#  schedule:
#    - cron: "*/15 * * * 1-6"

jobs:
  build-go:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build for Linux image
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for Windows image
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux image
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Install Apache2 on linux image
        run: sudo apt-get install apache2

      - name: Update linux image
        run: sudo apt-get update

      - name: Upload artifact for Windows image
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Linux Artifact
        uses: actions/download-artifact@v2
        with:
          name: linux

      - name: Make run.sh executable
        run: chmod +x ./run.sh

      - name: Run Script
        run: ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows

      - name: List files in current directory
        run: dir
      
      - name: Hello world
        run: |
          write-output "Hello World"
