name: Go Hello-Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2-6"  # Executa à meia-noite (UTC) de terça a sábado
    
env:
  FILE_NAME: hello-server
  
jobs:
  build-go:
    name: Build GO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GO Code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5.0.2  
    - name: Build ${{env.FILE_NAME}} for ubuntu-latest
      run: go build ${{env.FILE_NAME}}.go
    - name: Build ${{env.FILE_NAME}} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{env.FILE_NAME}}.go
    
  upload-job-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artefato no linux
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./${{env.FILE_NAME}}

  upload-job-windows:
    runs-on: windows-latest
    steps:
      - name: Upload artefato no windows
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./${{env.FILE_NAME}}.exe
          if-no-files-found: warn
          overwrite: true
