- name: Push a cada 15 minutos
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

    schedule:
      - cron: */15 * * * 1-6 echo "schedule push file" >/dev/null 2>&1

- name: Upload artifact for linux
    uses: actions/upload-artifact@v1.0.0
    with:
      name: linux
      path: ./${{ env.FILE_NAME }}
- name: Upload artifact for windows
    uses: actions/upload-artifact@v1.0.0
    with:
      name: windows
      path: ./${{ env.FILE_NAME }}.exe
